# -*- coding: utf-8 -*-
"""BrandonGonzalez_PGY1121_011_D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8AG5_bIYu0tS409eaG2TbgbKm4XK8Bp

Pantallazo de archivo en github
"""

import numpy as np

# DEFINICIONES #
def despedida():
  print("\nMuchas gracias por su visita, que tenga un buen día.")
  print("\n\nBrandon Gonzalez ver:0.1")
  return

def opcion_menu():
  try:
    print("Escoja una opcion del menú:\n")
    op_menu = int(input("\n(Seleccione una de las opciones que se mnuestran en pantalla.)\n"))
  except:
    op_menu = 0

##
nacimiento = "Certificado de nacimiento"
conyugal = "Certificado de estado conyugal"
europea = "Certificado de pertenencia a la Unión Europea"
menu3 = ""
##

#Switches#
sw_menu = True
sw_op3 = False
#

#Listas#
nif = [["99999999", "-RTX", "Brandon Gonzalez", 18],
       ["77777777", "-GRY", "Dor Ramon", 42],
      ["99945645", "-NTX", "asdada Gonzalez", 23]]

#
matriz = np.array(nif)

print(matriz)

print("Bienvenido al Registro de ciudadanos.\n")
while sw_menu == True:
  print("Escoja una opcion del menú:\n")
  print("1.-Grabar. ")
  print("2.-Buscar.")
  print("3.-Imprimir certificados.")
  print("4.-Salir.")
  try:
    op_menu = int(input("\n(Seleccione una de las opciones que se mnuestran en pantalla.)\n"))
  except:
    op_menu = 0
    continue

  if op_menu == 1:
    print("Funciona opcion 1")

  elif op_menu == 2:
    print("Funciona opcion 2")
  elif op_menu == 3:
    sw_op3 = True
    while sw_op3 == True:
      print("¿Que tipo de Certificado busca?")
      print("1.-Certificado de nacimiento.")
      print("2.-Certificado de estado conyugal.")
      print("3.-Certificado de pertenencia a la Unión Europea.")
      try:
        op_menu3 = int(input("\n(Seleccione una de las opciones que se mnuestran en pantalla.)\n"))
      except:
        op_menu3 = 0
        continue
      if op_menu3 == 1:
        menu3 = nacimiento
      elif op_menu3 == 2:
        menu3 = conyugal
      elif op_menu3 == 3:
        menu3 = europea
      if menu3 == nacimiento or menu3 == conyugal or menu3 == europea:
        print("-"*10,menu3,"-"*10)
        estado = input("Ingrese su estado conyugal:\t")
        pertenece = input("¿Pertenece a la union europea?(si/no):\t")
        print("NIF:\t", matriz[0,0],matriz[0,1])
        print("Nombre:\t",matriz[0,2])
        print("Edad:\t", matriz[0,3])
        sw_op3 = False
##Parte 4 lista (Borrar al final)
  elif op_menu == 4:
    despedida()
    break
  else:
    print("\nIngrese una opcion valida.\n")